language: php
php:
  - 5.3
  - 5.4
before_install:
  - composer install --dev
  - sudo service elasticsearch start
  - sleep 3
before_script:
  - sh tests/install-php-memcache.sh
  
services:
  - elasticsearch
  
script: ./runtests.sh
